{% set name = "jove" %}
{% set version = "4.17.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # This is an asset usually uploaded to the GitHub release by the maintainers:
  # https://github.com/jonmacs/jove/releases/download/{{ version }}/jove-{{ version }}.tgz
  # This is the (smaller) automatic snapshot of the files under version control:
  url: https://github.com/jonmacs/jove/archive/{{ version }}.tar.gz
  sha256: e28836e23001b79cd2d2e9e0174de426be46388e28b7086c57d3d072481af9b8
  patches:
    - windows.patch  # [win]

build:
  number: 1
  script: make JOVEHOME="%PREFIX%" SYSDEFS=-DMINGW XEXT=.exe EXTRAOBJS=win32.o install  # [win]
  script: make JOVEHOME="$PREFIX" SYSDEFS=-DDarwin TERMCAPLIB=-lncurses install  # [osx]
  script: make JOVEHOME="$PREFIX" SYSDEFS=-DLinux LDFLAGS="$LDFLAGS " TERMCAPLIB=-lncurses install  # [linux]

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - m2-inetutils  # [win]
    - make
    - groff  # [linux]
  host:
    - ncurses  # [not win]

test:
  commands:
    - which jove

about:
  home: https://github.com/jonmacs/jove/
  license: LicenseRef-JOVE
  license_file: LICENSE
  summary: JOVE - Jonathan's Own Version of Emacs
  description: |
    Jove is a compact, powerful Emacs-style text-editor. It provides the
    common emacs keyboard bindings, together with a reasonable assortment
    of the most popular advanced features (e.g. interactive shell windows,
    compile-it, language specific modes) while weighing in with CPU, memory,
    and disk requirements comparable to vi.

extra:
  recipe-maintainers:
    - peterjc
