{% set name = "jove" %}
{% set version = "4.17.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # This is an asset usually uploaded to the GitHub release by the maintainers:
  # https://github.com/jonmacs/jove/releases/download/{{ version }}/jove-{{ version }}.tgz
  # This is the (smaller) automatic snapshot of the files under version control:
  url: https://github.com/jonmacs/jove/archive/{{ version }}.tar.gz
  sha256: 3fd763625367962de39a66b8fa103b41e17c87d3a0bdf9cac7a93e26e135198c

build:
  number: 0
  skip: true  # [win]
  script: make -f Makefile.msc && cp jjove.exe "$PREFIX/bin/jove.exe"  # [win]
  script: make JOVEHOME="$PREFIX" SYSDEFS=-DDarwin install  # [osx]
  script: make JOVEHOME="$PREFIX" LDFLAGS="$LDFLAGS " TERMCAPLIB=-lncurses install  # [linux]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - ncurses  # [not win]

test:
  commands:
    - which jove

about:
  home: https://github.com/jonmacs/jove/
  license: LicenseRef-JOVE
  license_file: LICENSE
  summary: JOVE - Jonathan's Own Version of Emacs
  description: |
    Jove is a compact, powerful Emacs-style text-editor. It provides the
    common emacs keyboard bindings, together with a reasonable assortment
    of the most popular advanced features (e.g. interactive shell windows,
    compile-it, language specific modes) while weighing in with CPU, memory,
    and disk requirements comparable to vi.

extra:
  recipe-maintainers:
    - peterjc
